### ISSUE TITLE
[UR] Add PI changes to support multi-device contexts.

### ISSUE THREAD

**Issue by veselypeta** [oneapi-src/unified-runtime#437] opened 2023-04-11 10:11 UTC
intel/llvm#6446 introduces several changes to the PI interface - we should reflect these changes in unified runtime. This PR is still in-review so some changes may still occur.

Key Changes:
* new entry-point `piextGetMemoryConnection`
* new enum `pi_memory_connection`
* additional parameter `hDevice` is passed to `piMemBufferCreate` & `piMemImageCreate`

**Comment by kbenzie** [comment] 2023-04-11 13:00
I think this is a duplicate of #53

**Closed** 2023-04-11 13:00 UTC
Labels: pi, specification
