### ISSUE TITLE
SYCL builds of UR fail due to undefined reference to std::filesystem

### ISSUE THREAD

**Issue by bmyates** [oneapi-src/unified-runtime#451] opened 2023-04-18 15:17 UTC
After addition in #439 some SYCL builds of UR are failing with undefined reference to std::filesystem::__cxx11::path::_M_split_cmpts()`

See this comment:: https://github.com/intel/llvm/pull/9053#issuecomment-1510034425

**Comment by kbenzie** [comment] 2023-04-19 10:20
@bmyates I'd ideally like to replicate this build environment in our CI so we can catch these issues before they reach SYCL, is it documented somewhere?

**Comment by pbalcer** [comment] 2023-04-19 10:59
We could rip out the use of `std::filesystem` and replace it with two platform-specific implementations. It's not used for much. But I'm not sure if that's a good solution. UR's [README](https://github.com/oneapi-src/unified-runtime#building) states that it requires C++17, and also means a C++ standard library that adequately implements its features. If we can't rely on that, and we do truly need to support platforms with old compilers, I'd prefer we revert to C++14 instead of playing endless whack-a-mole to support compilers/standard libraries with bugs or partial implementations.

It's not reasonable to expect that UR (or any project) is bug-compatible with every compiler and standard library version. We need to have stable target platforms (e.g., whatever ships in some stable versions of RHEL, SUSE, and Debian).
How does SYCL approach this? [The getting started guide](https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedGuide.md#prerequisites) only lists `GCC version 7.1.0 or later`.

Also, I found [this](https://discourse.cmake.org/t/correct-way-to-link-std-filesystem-with-gcc-8/4121), which says that std::filesystem on GCC requires adding `-lstdc++fs`. I think this should solve the immediate problem.

**Comment by kbenzie** [comment] 2023-04-19 11:45
The C++17 requirement is inherited from upstream LLVM, I still think its reasonable for UR to also require it. I'd like to avoid reverting to C++14 if possible as `<filesystem>` is not the only instance of C++17 already in use.

This issue is frustrating though and I'd like to avoid getting bug reports from CI pipelines I'm not aware of moving forwards.

> It's not reasonable to expect that UR (or any project) is bug-compatible with every compiler and standard library version. We need to have stable target platforms (e.g., whatever ships in some stable versions of RHEL, SUSE, and Debian).
How does SYCL approach this? [The getting started guide](https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedGuide.md#prerequisites) only lists GCC version 7.1.0 or later.

Totally agree that we need to have a list of supported platforms, those at least need to line up with the ones in DPC++. Once we have that we can expand our CI and acceptance criteria for PRs to avoid recurrances moving forwards.

> Also, I found [this](https://discourse.cmake.org/t/correct-way-to-link-std-filesystem-with-gcc-8/4121), which says that std::filesystem on GCC 8 requires adding -lstdc++fs. I think this should solve the immediate problem.

These [lines](https://github.com/oneapi-src/unified-runtime/blob/main/CMakeLists.txt#L59-L62) in the root `CMakeLists.txt` should be setting `-lstdc++fs` globally for all UR targets but the link step for `ur_loader` doesn't have this option. I'll look into this.

**Comment by bmyates** [comment] 2023-04-19 17:03
> This issue is frustrating though and I'd like to avoid getting bug reports from CI pipelines I'm not aware of moving forwards.

I agree, it is frustrating for me as well.   I have requested a list of required platforms from SYCL but have not received an answer yet.

**Comment by andykaylor** [comment] 2023-04-20 23:34
I ran into this problem trying to build the SYCL compiler from the intel/llvm repository. I am using a RHEL8 system with gcc 8.3.1. It doesn't look like it's caused by a lack of C++17

**Comment by kbenzie** [comment] 2023-04-21 11:18
RHEL 8 is be based on Fedora 28 and I've managed to reproduce this error there, working on a fix.

**Comment by kbenzie** [comment] 2023-04-21 13:37
@bmyates / @andykaylor could you please verify the fix in #456 works as expected on the fialing RHEL builds?

**Comment by andykaylor** [comment] 2023-04-21 19:53
@kbenzie #456 does fix the problem for me. Thanks!

**Comment by kbenzie** [comment] 2023-04-24 09:35
Thanks @andykaylor, I'll merged the now.

I've created #457 to cover adding CI to try and avoid this reoccuring in future.

**Closed** 2023-04-24 10:38 UTC
